# Generated by Django 5.1.1 on 2024-09-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news_created_at_news_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('pending', 'pending'), ('verified', 'verified')], default='submitted', max_length=20),
        ),
    ]
