# Generated by Django 5.1.1 on 2024-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_verified',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
