# Generated by Django 5.1.1 on 2024-09-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_news_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
