# Generated by Django 5.1.1 on 2024-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_news_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feed_back_to_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
