# Generated by Django 5.1.1 on 2024-09-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog_feed_back_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('pending', 'pending'), ('verified', 'verified'), ('rejected', 'rejected')], default='submitted', max_length=20),
        ),
    ]
