# Generated by Django 5.1.1 on 2024-09-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'submitted'), ('pending', 'pending'), ('verified', 'verified'), ('rejected', 'rejected')], default='submitted', max_length=20),
        ),
    ]
