# Generated by Django 5.1.1 on 2024-09-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='feed_back_to_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
